# Generated by Django 5.2.8 on 2026-03-02 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.IntegerField(unique=True)),
                ('tmdbId', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('genres', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('directors', models.TextField(blank=True)),
                ('actors', models.TextField(blank=True)),
                ('poster_path', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
